In [3]:
import pandas as pd
import numpy as np
import os
import joblib
import matplotlib.pyplot as plt

In [74]:
class Perceptron():
    def __init__(self, eta: float = None, epocs: int = None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta # leraning rate
        self.epocs = epocs  # Nos of iteration
        
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self, z):
        return np.where(z>1,1,0)
        
    def fit(self, X,y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f'X with bias: \n{X_with_bias}')
        
        for epoc in range(self.epocs):
            
            print("--"*10)
            print(f"for epoc >> {epoc+1}")
            print("--"*10)
            
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f'predicted value after forward pass: \n{y_hat}')
            
            self.error = self.y - y_hat
            print(f'error: \n{self.error}')
            
            self.weights =self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f"update the weight after epoc: {epoc+1}/{self.epocs}: \n{self.weights}")
            print(f"##"*10)
            
            
    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X),1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)     
            
            
        

### OR gate implimented by using one Perceptron


In [75]:
OR = {
    "X1": [0,0,1,1],
    "X2": [0,1,0,1],
    'y': [0,1,1,1]
}

df_OR = pd.DataFrame(OR)

In [76]:
df_OR

X1  X2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [77]:
def prepare_data(df, target_col ='y'):
    X = df.drop(target_col, axis =1)
    y = df[target_col]
    return X,y

In [78]:
X,y =prepare_data(df_OR)
ETA = 0.1
EPOCS=10

model_or = Perceptron(eta=ETA, epocs=EPOCS)

In [79]:
model_or.fit(X,y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoc >> 1
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
update the weight after epoc: 1/10: 
[ 0.19998667  0.19998224 -0.30005476]
####################
--------------------
for epoc >> 2
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
update the weight after epoc: 2/10: 
[ 0.39998667  0.39998224 -0.60005476]
####################
--------------------
for epoc >> 3
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
update the weight after epoc: 3/10: 
[ 0.39998667  0.39998224 -0.60005476]
####################
--------------------
for epoc >> 4
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype:

In [80]:
model_or.predict(X)

array([0, 1, 1, 1])

### AND gate implimented by one Perceptron

In [88]:
AND = {
    "X1": [0,0,1,1],
    "X2": [0,1,0,1],
    'y': [0,0,0,1]
}

df_AND = pd.DataFrame(AND)

In [89]:
X,y =prepare_data(df_AND)
ETA = 0.1
EPOCS=10

model_and = Perceptron(eta=ETA, epocs=EPOCS)

model_and.fit(X,y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoc >> 1
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
update the weight after epoc: 1/10: 
[ 0.09995725  0.09990333 -0.10012543]
####################
--------------------
for epoc >> 2
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
update the weight after epoc: 2/10: 
[ 0.19995725  0.19990333 -0.20012543]
####################
--------------------
for epoc >> 3
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
update the weight after epoc: 3/10: 
[ 0.29995725  0.29990333 -0.30012543]
####################
--------------------
for epoc >> 4
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype:

In [90]:
model_and.predict(X)

array([0, 0, 0, 1])

### NOR gate implemented by one Preceptron

#### we can not get accurate result of NOR gate by one perceptro
#### due to Nor gate is non linear properties